name: "Trigger Deploy Workflow"
description: "Trigger deploy workflow via workflow_dispatch as tagging with GITHUB_TOKEN prevent upcoming event in Github Workflow from being triggered"
inputs:
  tag:
    description: "Tag for trigger"
    required: true
  workflow_id:
    description: "Workflow that will be triggered"
    required: true
  skip_dev:
    required: true
    description: Skip deploy to dev environment

runs:
  using: "composite"
  steps:
    - name: Trigger Tag Event
      uses: actions/github-script@v5
      with:
        script: |
          try {
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ inputs.workflow_id }}',
              ref: `refs/tags/${{ inputs.tag }}`,
              inputs: {
                tag: `${{ inputs.tag }}`,
                skip_dev: `${{ inputs.skip_dev }}`
              },
            })
            console.log(result);
          } catch(error) {
            console.error(error);
            core.setFailed(error);
          }
