name: 'Update Deploy Badge'
description: 'Updates a Gist with deployment badge info'
inputs:
  gist_id:
    description: 'The ID of the Gist to update'
    required: true
  gist_token:
    description: 'GitHub token with Gist write access'
    required: true
  gist_name:
    description: 'Gist file name'
    required: true
  message:
    description: 'Deployment badge message'
    required: true
  color:
    description: 'Badge color (e.g., green, red, yellow)'
    required: true
  environment:
    description: 'Environment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create badge JSON
      shell: bash
      run: |
        cat <<EOF > badge.json
        {
          "schemaVersion": 1,
          "label": "${{ inputs.environment }}",
          "message": "${{ inputs.version }}",
          "color": "${{ inputs.color }}"
          "namedLogo": "github"
        }
        EOF

    - name: Update Gist
      shell: bash
      run: |
        curl -X PATCH "https://api.github.com/gists/${{ inputs.gist_id }}" \
          -H "Authorization: token ${{ inputs.gist_token }}" \
          -H "Content-Type: application/json" \
          --data @- <<EOF
        {
          "files": {
            "${{ inputs.gist_name }}": {
              "content": "$(cat badge.json)"
            }
          }
        }
        EOF
