name: On Push Workflow
run-name: "[On Push] ${{ github.event.head_commit.message }}"

on:
  push:
    branches-ignore:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Save Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: out/
          retention-days: 1

  review-dev:
    runs-on: ubuntu-latest
    environment: review-dev
    concurrency:
      group: review-dev
      cancel-in-progress: true
    needs: build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-result
      - name: Logging Approval
        shell: bash
        run: |
          echo "Approved!"

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    concurrency:
      group: deploy-dev
      cancel-in-progress: true
    needs: review-dev
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-result
          path: out
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: dev
          projectId: "${{vars.FIREBASE_PROJECT_ID}}"
