name: On Push Workflow
run-name: "[On Push] ${{ github.event.head_commit.message }}"

on:
  push:
    branches-ignore:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
